language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-28.0.3
    - android-28

script: echo -e 'explorer_github_app_id="app_id"\nexplorer_github_app_secret="secret"' > ~/.gradle/gradle.properties && ./gradlew build
